from mcp.server.fastmcp import FastMCP
import requests

import os

# FastMCP Server connecting LLMs to the local Quote Generator API
mcp = FastMCP("Quote Generator MCP")
BASE_URL = os.environ.get("QUOTE_API_URL", "http://127.0.0.1:5000/api/v1")

@mcp.tool()
def get_media_library() -> dict:
    """
    Lists all previously generated images, audio files (tts), and videos stored in the backend library.
    Useful to find filenames before creating a video.
    """
    try:
        r = requests.get(f"{BASE_URL}/library", timeout=10)
        return r.json()
    except Exception as e:
        return {"error": str(e), "message": "Make sure the Quote Generator Flask app is running on port 5000."}

@mcp.tool()
def generate_quote_image(text: str = "", author: str = "") -> dict:
    """
    Generates a beautiful motivational quote image with dynamic background.
    If text and author are left empty, it fetches a random inspirational quote.
    Returns the generated filename.
    """
    try:
        r = requests.post(f"{BASE_URL}/generate/image", json={"text": text, "author": author}, timeout=20)
        return r.json()
    except Exception as e:
        return {"error": str(e), "message": "Make sure the Quote Generator Flask app is running on port 5000."}

@mcp.tool()
def generate_tts_audio(text: str) -> dict:
    """
    Generates a text-to-speech audio file (mp3) in French from the provided text.
    Returns the generated filename.
    """
    try:
        r = requests.post(f"{BASE_URL}/generate/tts", json={"text": text}, timeout=20)
        return r.json()
    except Exception as e:
        return {"error": str(e), "message": "Make sure the Quote Generator Flask app is running on port 5000."}

@mcp.tool()
def generate_quote_video(image_filenames: list[str], audio_filename: str = None) -> dict:
    """
    Stitches generated images and an optional audio file together into an MP4 video.
    
    Args:
        image_filenames: A list of image filenames (e.g., ['quote_abc.jpg', 'quote_xyz.jpg']) 
                         that exist in the library.
        audio_filename: (Optional) The mp3 filename generated by generate_tts_audio to be used as BGM/speech.
    """
    payload = {"images": image_filenames}
    if audio_filename:
        payload["audio"] = audio_filename
        
    try:
        r = requests.post(f"{BASE_URL}/generate/video", json=payload, timeout=60)
        return r.json()
    except Exception as e:
        return {"error": str(e), "message": "Make sure the Quote Generator Flask app is running on port 5000."}

@mcp.tool()
def generate_wikipedia_story(subject: str) -> dict:
    """
    Given a subject, fetches a summary from Wikipedia, creates several text-overlaid images,
    generates a voiceover text-to-speech, and stitches them together into an animated MP4 video.
    Returns the generated video filename and a URL to view it.
    """
    try:
        r = requests.post(f"{BASE_URL}/generate/wiki-story", json={"subject": subject}, timeout=300)
        return r.json()
    except Exception as e:
        return {"error": str(e), "message": "Make sure the Quote Generator Flask app is running on port 5000."}

if __name__ == "__main__":
    import os
    transport = os.getenv("MCP_TRANSPORT", "stdio")
    if transport == "sse":
        port = int(os.getenv("MCP_PORT", "8002"))
        print(f"Starting Quote Generator FastMCP Server via SSE on port {port}...")
        mcp.run(transport="sse", host="0.0.0.0", port=port)
    else:
        print("Starting Quote Generator FastMCP Server via StdIO...")
        mcp.run()
